# Generated by Django 3.2.8 on 2021-10-05 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Permissão',
                'verbose_name_plural': 'Permissões',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('number', models.CharField(max_length=10, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('permissions', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.permissions')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'ordering': ['name', 'number'],
            },
        ),
    ]
