# Generated by Django 3.2.7 on 2021-10-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['age'],
            },
        ),
    ]
